initial commit
atlp-rwanda/phantom-be-dream-team pull request #12
Opened 2022-06-20 20:53 UTC by Benafrica

What does this PR do?

register drivers and operators

Description of Task to be completed?

1)The driver or operator should be able to sign in to the app using their email and the provided password.
2)Appropriate error messages are displayed on unsuccessful attempts
3)The administrator should be able to register a new driver or a new operator.
4)An email containing a random password should be sent to the provided email.

Have the following endpoint working

POST /users/register

How should this be manually tested?

git pull this branch
run npm install
check env.example file and add DEV_DATABASE_URL and JWT_SECRET  and USER_EMAIL IN to your .env file
Do migrations with npm run migrate
run npx sequelize-cli db:seed:all to create pre-configured credentials for seeders
run npm run start
Test the route POST /users/register in POSTMAN or any other platform for using API
Any background context you want to provide?
I used the JWT package for hashing the password stored in the Database

What are the relevant pivotal tracker stories?

https://trello.com/c/jcZ6Wev3/10-register-drivers-operators

Questions:
No.

2022-06-23 10:50 UTC, songa1 reviewed
Can you use bcryptjs?

2022-06-26 08:43 UTC, songa1 reviewed
Please increase your coverage. And fix tests which are failing.

2022-06-27 13:00 UTC, gyssa-prince requested changes

2022-06-27 13:00 UTC, gyssa-prince commented on package.json
> +    "test": "mocha --recursive --exit --timeout 1000000 --require @babel/register src/tests/index.test.js ",
point to all in test files ( .test.js)  instead of index.test.js only

2022-07-01 09:50 UTC, songa1 approved these changes

2022-07-01 09:57 UTC, arthurjunior250 approved these changes

2022-07-04 15:26 UTC, Stevenkwizera06 approved these changes

2022-07-04 16:04 UTC, merged