feature(Buses): Crud operation for buses
atlp-rwanda/phantom-be-dream-team pull request #14
Opened 2022-06-23 17:31 UTC by Stevenkwizera06

What does this PR do?

CRUD operations for buses

Description of Task to be completed?
- The operator should be able to create, update, and delete  a bus
- The operator should be able to view a paginated list of buses in the system
- Users should be able to view the bus's details
- Appropriate error messages are displayed on unsuccessful attempts

Have the following endpoint working

POST /api/v1/buses
GET /api/v1/buses
PUT /api/v1/buses/:id
DELETE /api/v1/buses/:id

How should this be manually tested?

git pull this branch
run npm install
Do migrations with npm run migrate
run npm run dev
Test the route POST /api/v1/buses in POSTMAN or any other platform for using API

Any background context you want to provide?
-N/A

What are the relevant pivotal tracker stories?

-https://trello.com/c/dF9at79J/11-crud-operations-for-buses

Questions:

-N/A

[ WIP #11 ]

2022-06-27 12:01 UTC, Juleshb approved these changes

2022-06-27 12:54 UTC, gyssa-prince requested changes
Can you uncomment these

2022-06-27 12:54 UTC, gyssa-prince commented on src/tests/buses.test.js
> +        // it('Enter valid plate number', (done) => {
Can you uncomment these tests to increase coverage

2022-06-27 13:39 UTC, songa1 reviewed
Everything is working except for the update and protecting your routes. Please work on that ASAP/

2022-06-27 13:39 UTC, songa1 commented on src/controllers/bus.js
> +        Bus
Is this what needs to be updated. It does not work, maybe you can use `bus.update` instead of `Bus.update`

2022-06-27 13:39 UTC, songa1 commented on src/controllers/bus.js
> +              message: "bus exits"
Please show the actual error here. Bus exits does not make any sense.

2022-06-27 20:32 UTC, songa1 approved these changes

2022-06-27 20:36 UTC, songa1 approved these changes

2022-06-28 06:09 UTC, gyssa-prince approved these changes

2022-06-28 10:59 UTC, merged