#20 Chore:Support multiple languages
atlp-rwanda/phantom-be-dream-team pull request #3
Opened 2022-06-09 11:52 UTC by Stevenkwizera06

**What does this PR do?**
   - Supports the app to use multiple languages
   
**Description of Task to be completed?**
  -Users should be able to change/select a language of their choice
  -The site contents are presented in the newly set language
  -At least, two languages are supported

**How should this be manually tested?**

  -Clone the repo
  -checkout to branch ch-support-multiple-language-20
  -Run npm install  to install modules
  -Run npm run dev:start to start the development server
  
    **Go to your postman**
  - Open postman and  run  GET http://localhost:3000
  - Go to headers in your postman :
              . On the Key Accept-language
              . On the value put :
                         - en for English
                         - fr for French
                         - kiny for Kinyarwanda
                         - sw for Swahili
  

  What are the relevant Pivotal Tracker/trello stories?
  - https://trello.com/c/wuUqiacL/20-support-multiple-languages
  
  **Screenshots**
  
 
<img width="1440" alt="Screen Shot 2022-06-09 at 13 48 30" src="https://user-images.githubusercontent.com/94446528/172839947-327eef91-4a96-4dfb-8f2a-59aefaa3c42b.png">

<img width="1440" alt="Screen Shot 2022-06-09 at 13 48 57" src="https://user-images.githubusercontent.com/94446528/172840037-6b488dae-edbf-48a5-88de-70358ab9bea6.png">

<img width="1440" alt="Screen Shot 2022-06-09 at 13 49 21" src="https://user-images.githubusercontent.com/94446528/172840104-576f329c-e99b-4592-8ed1-46bbf69df46a.png">

<img width="1440" alt="Screen Shot 2022-06-09 at 13 49 37" src="https://user-images.githubusercontent.com/94446528/172840295-28a694d9-3bf1-4bf9-b036-69c917aeda36.png">

2022-06-09 13:56 UTC, songa1 requested changes

2022-06-09 13:56 UTC, songa1 commented on src/app.js
> +i18next
I suggest putting these settings for internationalization in a separate file.

2022-06-13 14:43 UTC, arthurjunior250 approved these changes

2022-06-13 14:46 UTC, Juleshb approved these changes

2022-06-14 07:38 UTC, gyssa-prince approved these changes

2022-06-14 07:59 UTC, songa1 approved these changes

2022-06-14 07:59 UTC, merged