Ch setup continous continous integration #18
atlp-rwanda/phantom-be-dream-team pull request #5
Opened 2022-06-09 13:01 UTC by gyssa-prince

#### What does this PR do?

Configure a continuous integration pipeline using GitHub Actions and Heroku

#### Description of Task to be completed?

-Configured Testing environment with Mocha, Chai and Sinon to ensure that all functionalities are tested before deployment.
-GitHub Actions is configured as a continuous integration service used to build and test the app.
-Configured Heroku Pipeline on Heroku
-GitHub Actions  badge has been added to your repo
-Configure CodeClimate for code analysis and Maintainability checking.

How should this be manually tested?

-clone repo
-run npm install
-git checkout ch-setup-continous-continous-integration-#18
-npm run dev:start

Any background context you want to provide?

-N/A

What are the relevant pivotal tracker stories?

-Link:https://trello.com/c/zOdtLb0m

Screenshots (if appropriate)

<img width="1440" alt="Screen Shot 2022-06-12 at 13 43 42" src="https://user-images.githubusercontent.com/88536742/173231592-0e1849ed-8b7c-480b-9b1e-34e44309c2b4.png">

2022-06-13 08:29 UTC, arthurjunior250 commented on ReadMe.md
> +![Codecov](https://img.shields.io/codecov/c/github/atlp-rwanda/phantom-be-dream-team/ch-setup-continous-continous-integration-#18)
if it is possible, you can try to use code climate on code coverage

2022-06-13 10:07 UTC, songa1 requested changes
After all this is done, I suppose it will be ready to be merged.

2022-06-13 10:07 UTC, songa1 commented on .github/workflows/node.js.yml
> +    branches: [ ch-setup-continous-continous-integration-#18 ]
Can you add more branches? Preferable your branch and develop branch. So as to allow them to trigger the workflow run.

2022-06-13 10:07 UTC, songa1 commented on .github/workflows/node.js.yml
> +      run: npm test -- --coverage
Is this the right script to run test and coverage? I saw that they are different in `package.json`

2022-06-13 10:07 UTC, songa1 commented on ReadMe.md
> +![Codecov](https://img.shields.io/codecov/c/github/atlp-rwanda/phantom-be-dream-team/ch-setup-continous-continous-integration-#18)
You are using only this branch in this coverage badge? It might cause the problem when we get to other branches. Check out Arthur's comment above.

2022-06-14 11:09 UTC, songa1 approved these changes

2022-06-14 11:41 UTC, Juleshb approved these changes

2022-06-14 12:00 UTC, mukunzidd requested changes
The `.DS_Store` file should be in .gitignore otherwise you should be good to go

2022-06-15 09:06 UTC, shemalucien approved these changes

2022-06-15 09:17 UTC, mukunzidd approved these changes

2022-06-15 09:17 UTC, merged