feature(resetPassword):Reset password
atlp-rwanda/phantom-be-dream-team pull request #8
Opened 2022-06-15 17:00 UTC by Stevenkwizera06

What does this PR do?

Supports the app to use multiple languages
Description of Task to be completed?
  -The driver or operator should be able to receive a reset password link in their email
  -The driver or operator should be able to reset the password( i.e. provide a new password)
  -The driver or operator should be able to login with the new password
  -Appropriate error messages are displayed on unsuccessful attempts

How should this be manually tested?

-Clone the repo
-checkout to branch ft-reset-password-22
-Run npm install to install modules
-Run npm run dev:start to start the development server

**Go to your postman**
   -Open postman and run POST http://localhost:3000/forgotpassword
   -Go to Body in your postman  select JSON
   - put there the email ("email":"you@gmail.com")

**What are the relevant Pivotal Tracker/trello stories?**
    https://trello.com/c/4rvcKszD/22-reset-password

Screenshots

WIP #22

2022-06-20 11:54 UTC, songa1 requested changes
Can you first specify which Environment variables we need to be able to reset password?

Second, please catch errors. When there is an exception, it keeps loading and we need to see errors if we are going to solve them.

It appears to me that you did not work on tests.

2022-06-20 11:54 UTC, songa1 commented on src/app.js
> +server.use(forgotPasssword)
Like I said, this should not be here. Please use `/routes/index.js` for this.

2022-06-20 11:54 UTC, songa1 commented on src/controllers/forgotPassword.js
> +import  jwt from "jsonwebtoken";
It would be better if you put your controllers in one folder since you have two files.

2022-06-20 11:54 UTC, songa1 commented on src/routes/resetPassword.js
> +router.post('/api/v1/reset/:token', resetAuth, resetPassword)
`/api/v1` should not be here too.

2022-06-29 08:42 UTC, Juleshb approved these changes

2022-06-29 08:51 UTC, Juleshb approved these changes

2022-06-29 09:11 UTC, arthurjunior250 approved these changes

2022-06-29 09:36 UTC, gyssa-prince approved these changes

2022-06-29 10:12 UTC, merged