Ft update profile #38
atlp-rwanda/phantom-be-dream-team pull request #9
Opened 2022-06-17 07:34 UTC by gyssa-prince

What does this PR do?

As **operator or driver**, I want to be able to update information on my profile, so that others could see updated information about me.

Description of Task to be completed?
-The operator and driver should be able to update information about their own profile.
-The operator and driver profile should be able accessible publicly.
-Appropriate error messages are displayed on unsuccessful attempts.

How should this be manually tested?

-Clone the repo
-checkout to branch ft-update-profile-#38
-Run npm install to install modules
-Run npm run dev:start to start the development server

Go to your postman
**To see the profile of user**
-Open postman and run POST http://localhost:3000/profile/id of user
**To update the profile of user**
-Open postman and run POST http://localhost:3000/profile/update/id of user
-Go to Body in your postman select JSON

put there anything you want to edit in only these info (name,email,phone,password)("name":"your name","phone":"your new phoneNo")
your will see a message which says "Profile updated" and status code of 200 if succeed

**To see if your information has been update**
-Open you postman and run POST http://localhost:3000/profile/id of user  
or go to your database table and see if data has changed

What are the relevant Pivotal Tracker/trello stories?
https://trello.com/c/w1ftSCaI

**Screenshots**
<img width="1440" alt="Screen Shot 2022-06-17 at 09 31 24" src="https://user-images.githubusercontent.com/91846911/174248760-9d00f481-6650-42fe-b376-b460bb7c5c9f.png">

2022-06-20 09:33 UTC, Benafrica approved these changes

2022-06-20 11:37 UTC, songa1 requested changes
Check out some requested changes. And from what I have seen, you haven't written tests. If you did, there are some errors.

2022-06-20 11:37 UTC, songa1 commented on src/controllers/user.js
> +import model from '../models';
This is raising errors and when there is an error, it keeps loading. So, please find a way to catch those errors.

2022-06-20 11:37 UTC, songa1 commented on src/routes/index.js
Please make use of this file.

2022-06-20 11:37 UTC, songa1 commented on src/app.js
> +server.use("/profile",userRoute);
Do not put this here directly! Please use the file `/routers/index.js` to hold all of routes.

2022-06-23 11:25 UTC, songa1 reviewed
Please rebase and get recent changes.

2022-06-24 08:47 UTC, songa1 approved these changes

2022-06-24 09:57 UTC, Stevenkwizera06 approved these changes

2022-06-24 10:01 UTC, Juleshb approved these changes

2022-06-24 11:32 UTC, arthurjunior250 approved these changes

2022-06-26 08:06 UTC, songa1 requested changes
Please fix your tests. Even though you disabled them, they are even failing locally Refer to the resources I shared in the channel, and it would be better if you don't use real data while testing. Meaning that you don't need to use the development database while testing.

2022-06-26 08:06 UTC, songa1 commented on package.json
> +    "test": "mocha --recursive --exit --timeout 1000000 --require @babel/register src/tests/index.test.js ",
And please change this script. You are referring test located in index.test.js which we don't have.

You should be reffering to every file in /src/tests/

2022-06-28 06:35 UTC, songa1 approved these changes

2022-06-28 06:36 UTC, merged